# Image R + tidyverse déjà installés
FROM rocker/tidyverse:4.3.2

# Installer dépendances système pour Bioconductor
RUN apt-get update && apt-get install -y --no-install-recommends \
    libxml2-dev libssl-dev libcurl4-openssl-dev \
    && rm -rf /var/lib/apt/lists/*

# Installer Bioconductor + DESeq2 et outils connexes
RUN R -e "install.packages('BiocManager'); \
           BiocManager::install(c('DESeq2', 'edgeR', 'limma', 'tximport', 'apeglm', \
           'biomaRt', 'SummarizedExperiment', 'GenomicFeatures', 'airway'), ask = FALSE)"

WORKDIR /home

CMD ["R"]
